title: Santosh Wadghule
description: >
  Ruby, Ruby on Rails, JavaScript fullstack developer, DevOps and Vim lover. # We use it in head title tag.
author:
  name: mechanicles
  email: santosh.wadghule@gmail.com
  about_me: >
    A full-stack Ruby developer based out of Pune. Love Ruby, JavaScript,
    Open Source Software and Vim.
  twitter: mechanicles
  github: mechanicles

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.mechanicles.com/" # the base hostname & protocol for your site

twitter_username: mechanicles
github_username:  mechanicles
linkedin_username: santosh-wadghule
rss: rss

show_excerpts: true

disqus:
  shortname: santosh-wadghule

twitter:
  card: summary
  username: mechanicles

google_analytics: UA-84554051-1

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-octicons
  - jekyll-sitemap
