# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Santosh Wadghule
email: santosh.wadghule@gmail.com
description: >
  Ruby, Ruby on Rails, JavaScript fullstack developer, DevOps and Vim lover.
author:
  about_me: >
    A full-stack Ruby developer based out of Pune. Love Ruby, JavaScript,
    Open Source Software and Vim.
  twitter: mechanicles
  github: mechanicles

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.mechanicles.com/" # the base hostname & protocol for your site
twitter_username: mechanicles
github_username:  mechanicles

twitter:
  card: summary
  username: mechanicles

google_analytics: UA-84554051-1

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-octicons
  - jekyll-sitemap
